#!/usr/bin/env python3
"""Build a CCS project: SysConfig CLI -> gmake (auto-generates makefile if needed)."""
from __future__ import annotations

import json
import shutil
import subprocess
from pathlib import Path


def _load_config(config_path: str) -> dict:
    with open(config_path, encoding="utf-8") as f:
        return json.load(f)


def _generate_makefile(ticlang_dir: Path, proj: Path, config: dict) -> None:
    """Generate a minimal makefile for CLI builds (CCS IDE does this automatically)."""
    sdk_root = Path(config.get("sdk_root", ""))
    compiler_bin = Path(config.get("compiler", "")) / "bin"

    # Collect ALL .c files recursively (excluding Debug, ticlang, targetConfigs)
    skip_dirs = {"Debug", "ticlang", "targetConfigs", ".settings"}
    c_files_rel = []
    include_dirs = set()
    for cf in sorted(proj.rglob("*.c")):
        if any(s in cf.parts for s in skip_dirs):
            continue
        rel = cf.relative_to(proj)
        c_files_rel.append(rel)
        if rel.parent != Path("."):
            include_dirs.add(str(rel.parent))

    if not c_files_rel:
        raise FileNotFoundError("No .c source files found in project")

    # Also add subdirs that have .h files only (for include paths)
    for d in sorted(proj.rglob("*")):
        if d.is_dir() and not any(s in d.parts for s in skip_dirs):
            if list(d.glob("*.h")):
                rel = d.relative_to(proj)
                include_dirs.add(str(rel))

    inc_flags = " ".join(f"-I../{d}" for d in sorted(include_dirs))

    c_files = [str(f).replace("\\", "/") for f in c_files_rel]

    # Find startup file
    startup_src = sdk_root / "source/ti/devices/msp/m0p/startup_system_files/ticlang/startup_mspm0g351x_ticlang.c"
    startup_dst = ticlang_dir / "startup_mspm0g351x_ticlang.c"
    if startup_src.exists():
        shutil.copy2(startup_src, startup_dst)
        c_files.append("startup_mspm0g351x_ticlang.c")

    # Copy device_linker.cmd
    linker_src = sdk_root / "examples/nortos/LP_MSPM0G3519/driverlib/gpio_toggle_output/ticlang/device_linker.cmd"
    if not linker_src.exists():
        linker_src = sdk_root / "source/ti/devices/msp/m0p/linker_files/ticlang/mspm0g3519.cmd"
    linker_dst = ticlang_dir / "device_linker.cmd"
    if linker_src.exists():
        shutil.copy2(linker_src, linker_dst)

    # Generate makefile
    makefile = f"""# Auto-generated by build.py
MSPM0_SDK_INSTALL_DIR = {sdk_root}
TICLANG_ARMCOMPILER    = {compiler_bin}
CC   = "${{TICLANG_ARMCOMPILER}}/tiarmclang"
LNK  = "${{TICLANG_ARMCOMPILER}}/tiarmclang"

CFLAGS = -I.. -I. @INCLUDE_DIRS@ \\
    -I"${{MSPM0_SDK_INSTALL_DIR}}/source/third_party/CMSIS/Core/Include" \\
    -I"${{MSPM0_SDK_INSTALL_DIR}}/source" \\
    -D__MSPM0G3519__ -gdwarf-3 -mcpu=cortex-m0plus -march=thumbv6m \\
    -mfloat-abi=soft -mthumb -O2

LFLAGS = -Wl,--rom_model -Wl,--warn_sections \\
    -L"${{MSPM0_SDK_INSTALL_DIR}}/source" \\
    -L.. -L. \\
    -Wl,-l"{linker_dst.name}" \\
    -ldevice.cmd.genlibs \\
    -L"${{TICLANG_ARMCOMPILER}}/lib" \\
    -llibc.a

OBJECTS = {' '.join(Path(cf).stem + '.o' for cf in c_files)}
NAME    = {proj.name}

all: $(NAME).out

$(NAME).out: $(OBJECTS)
\t@echo linking $@
\t$(LNK) $(OBJECTS) $(LFLAGS) -o $(NAME).out

"""
    for cf in c_files:
        stem = Path(cf).stem
        src_path = f"../{cf}".replace("\\", "/")
        makefile += f"{stem}.o: {src_path}\n"
        makefile += f"\t$(CC) $(CFLAGS) -c {src_path} -o $@\n\n"

    makefile += "clean:\n\trm -f $(OBJECTS) $(NAME).out $(NAME).map\n"
    (ticlang_dir / "makefile").write_text(makefile, encoding="utf-8")


def main(
    project_dir: str,
    config_path: str | None = None,
    _interactive: bool = True,
) -> tuple[bool, str]:
    config = _load_config(
        config_path or str(Path(__file__).resolve().parents[1] / "config.json")
    )

    proj = Path(project_dir).resolve()
    syscfg_files = list(proj.glob("*.syscfg"))
    if not syscfg_files:
        return False, f"No .syscfg file found in {proj}"
    syscfg = syscfg_files[0]

    sysconfig_cli = config.get("sysconfig_cli", "sysconfig_cli.bat")
    gmake = config.get("gmake", "gmake")
    sdk_root = config.get("sdk_root", "")
    product_json = str(Path(sdk_root) / ".metadata" / "product.json")

    # Step 1: SysConfig
    if _interactive:
        response = input(
            f"\nRun SysConfig CLI? (y/n)\n"
            f"  Path: {sysconfig_cli}\n"
            f"  Target: {syscfg}\n"
        )
        if response.lower() not in ("y", "yes", ""):
            return False, "User declined SysConfig step"

    sysconfig_cmd = [
        sysconfig_cli, "--compiler", "ticlang",
        "--product", product_json, "--output", str(proj), str(syscfg),
    ]
    print(f"[SysConfig] {' '.join(sysconfig_cmd)}")
    result = subprocess.run(sysconfig_cmd, capture_output=True, text=True, cwd=str(proj))
    if result.returncode != 0:
        return False, f"SysConfig failed:\n{result.stderr}\n{result.stdout}"

    # Step 2: Ensure ticlang/ exists (auto-generate makefile if needed)
    ticlang_dir = proj / "ticlang"
    if not ticlang_dir.is_dir():
        ticlang_dir.mkdir(exist_ok=True)
        _generate_makefile(ticlang_dir, proj, config)

    if _interactive:
        response = input(f"\nRun gmake? (y/n)\n  Dir: {ticlang_dir}\n")
        if response.lower() not in ("y", "yes", ""):
            return False, "User declined gmake step"

    gmake_cmd = [gmake, "-C", str(ticlang_dir)]
    print(f"[gmake] {' '.join(gmake_cmd)}")
    result = subprocess.run(gmake_cmd, capture_output=True, text=True, cwd=str(ticlang_dir))

    if result.returncode != 0:
        return False, f"gmake failed:\n{result.stderr}\n{result.stdout}"

    out_files = list(ticlang_dir.glob("*.out"))
    out_path = str(out_files[0]) if out_files else f"{ticlang_dir}/{proj.name}.out"
    return True, out_path


if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser(description="Build CCS project")
    parser.add_argument("project_dir", help="Path to project directory")
    parser.add_argument("-y", "--yes", action="store_true", help="Skip interactive prompts")
    parser.add_argument("--rebuild", action="store_true", help="Delete ticlang/ and regenerate makefile from scratch")
    args = parser.parse_args()
    if args.rebuild:
        import shutil
        ticlang = Path(args.project_dir) / "ticlang"
        if ticlang.exists():
            shutil.rmtree(ticlang)
            print("[rebuild] removed ticlang/ for fresh regeneration")
    ok, msg = main(args.project_dir, _interactive=not args.yes)
    if ok:
        print(f"\nBuild successful\n  Output: {msg}")
    else:
        print(f"\nBuild failed\n{msg}")
        raise SystemExit(1)
